/* eslint-disable @next/next/link-passhref */
import type { NextPage } from 'next'
import Head from 'next/head'
import SideBar from '../components/drawer'
import Card from '../components/Card'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import AsyncSelect from 'react-select/async';
import React, { useState } from 'react'
import Typography from '@mui/material/Typography';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import FormControl from '@mui/material/FormControl';

interface country {
  capital: number
  currency: string
  flag: string
  name: string
  population: string
  id: number
  visited ?: boolean
}

export const getServerSideProps: any = async () => {
  const res = await fetch("http://localhost:3000/api/list")
  const countries = await res.json()
  if (!countries) {
    return {
      notFound: true
    }
  }

  return {
    props: countries
  }
}

const Home: NextPage = (props: any) => {

  const countries = props.countries
  console.log(countries)
  const [age, setAge] = useState('');

  const handleChangeFilter = (event: SelectChangeEvent) => {
    setAge(event.target.value as string);
    console.log(event.target.value)
  };

  const [country, setCountry] = useState<string | country>('');
  const [selectedValue, setSelectedValue] = useState<string | null>(null);



  // handle input change event
  const handleInputChange = (value: any) => {
    setCountry(value);
  };

  // handle selection
  const handleChange = (value: string) => {
    setSelectedValue(value);
  }

  const AddCountry = async (country: any) => {


    console.log(country)
    if (country != null) {
      const cnt = {
        capital: country.capital,
        currency: country.currencies[0].code,
        flag: country.flag,
        name: country.name,
        population: country.population,
      }
      const res = await fetch('http://localhost:3000/api/addList',
        {
          body: JSON.stringify({
            info: cnt
          }),
          headers: {
            'Content-Type': 'application/json'
          },
          method: 'POST'
        }
      )
      const result = await res.json();
      console.log(result)
    }
  }

  const loadOptions = async (inputValue: string) => {
    return fetch(`https://restcountries.com/v2/name/${inputValue}`).then(res => res.json());
  };

  const j = [1, 2, 3, 4, 5]

  return (

    <Box
      sx={{
        display: 'grid',
        gridAutoColumns: '2fr',
      }}
    >
      <SideBar />
      <Head>
        <title>Bag Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid item gridColumn={{ lg: '2/5', sm: '2/5' }} sx={{ display: 'block', marginLeft: 5 }}  >

        <Grid item container xs={12} spacing={2}>
          <Grid item md={3} xs={6}>
            <Typography variant="h4" noWrap style={{ "marginLeft": "15px", "marginRight": "2px" }} >
              MY LIST
            </Typography>
          </Grid>

          <Grid item md={6} xs={2} style={{ "marginLeft": "5px" }}>

          </Grid>
        </Grid>



        <Grid container spacing={1}>
          <Grid item md={4} xs={6} sm={6}>
            <AsyncSelect
              onInputChange={handleInputChange}
              onChange={handleChange}
              getOptionLabel={(e: any) => e.name}
              getOptionValue={(e: any) => e.name}
              instanceId="manager"
              id="manager"
              loadOptions={loadOptions}
            />
          </Grid>

          <Grid item md={2} xs={6} sm={6} >
            <Button
              variant="contained"
              onClick={() => AddCountry(selectedValue)}
            >Add to list
            </Button>
          </Grid>
          <Grid item md={2} sm={3} xs={3} >
            <FormControl fullWidth>
              <InputLabel>Filter</InputLabel>
              <Select
                labelId="demo-simple-select-label"
                id="demo-simple-select"
                value={age}
                label="Age"
                onChange={handleChangeFilter}
              >
                <MenuItem value="Africa">Africa</MenuItem>
                <MenuItem value="Europe">Europe</MenuItem>
                <MenuItem value="Asia">Asia</MenuItem>
                <MenuItem value="Asia">Oceania</MenuItem>
                <MenuItem value="America">America</MenuItem>
              </Select>
            </FormControl>
          </Grid>
        </Grid>

        <Container sx={{ display: 'block', marginTop: 4 }}>
          <Grid item container spacing={1}>
            {countries.map((i:country) =>
              <Grid item key={i.id} lg={3} md={4} sm={12} xs={12} >
                <Card key={i} id={i.id} info={i} />
              </Grid>
            )}
          </Grid>
        </Container>

      </Grid >
    </Box >
  )
}

export default Home
